const LOG_LEVEL = {
  SEVER: 1,
  CLIENT_SERVER: 2,
};

const HTTP_CODE = {
  SUCCESS: 200,
  BAD_REQUEST: 400,
  NOT_FOUND: 404,
  VALIDATION_ERROR: 422,
  SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
};

const RESPONSE_CODE = {
  SUCCESS_LOGIN: 'SUCCESS_LOGIN',
  SUCCESS_LOGOUT: 'SUCCESS_LOGOUT',
  SUCCESS_POST_REQUEST: 'SUCCESS_POST_REQUEST',
  SUCCESS_PATCH_REQUEST: 'SUCCESS_PATCH_REQUEST',
  SUCCESS_GET_REQUEST: 'SUCCESS_GET_REQUEST',
  SUCCESS_PUT_REQUEST: 'SUCCESS_PUT_REQUEST',
  SUCCESS_DELETE_REQUEST: 'SUCCESS_DELETE_REQUEST',
};

const ERROR_CODE = {
  ERROR_UNDEFINED: 'ERROR_UNDEFINED',
  ERROR_VALIDATION: 'ERROR_VALIDATION',
  ERROR_NOT_FOUND: 'ERROR_NOT_FOUND',
  ERROR_PARAM_REQUEST: 'RROR_PARAM_REQUEST',
  ERROR_DUPICATE_REQUEST: 'ERROR_DUPICATE_REQUEST',
  ERROR_SERVICE_UNAVAILABLE: 'ERROR_SERVICE_UNAVAILABLE',
  ERROR_PARAM_TOO_LONG: 'ERROR_PARAM_TOO_LONG',
  ERROR_REQUEST_TOO_LARGE: 'ERROR_REQUEST_TOO_LARGE',
  INVALID_URL: 'INVALID_URL',
  INVALID_TIMEOUT: 'INVALID_TIMEOUT',
  INVALID_METHOD: 'INVALID_METHOD',
  EXPIRED: 'EXPIRED',
  INFO_DATA_NOT_FOUND: 'INFO_DATA_NOT_FOUND',
  ERROR_SERVER: 'INTERNAL_SERVER_ERROR',
  DUPLICATE_DATA: 'DUPLICATE_DATA',
};

module.exports = {
  LOG_LEVEL,
  HTTP_CODE,
  RESPONSE_CODE,
  ERROR_CODE,
};


